### PR TITLE
using $.extend instead lodash

### PR DESCRIPTION
**Pull request by yaoazhen**
remove lodash  from product dependance

### CODE REVIEW

**Comment by mikaelkaron** [comment]
Do you need a new version published for this or are you ok with running #develop for now?

**Comment by yaoazhen** [comment]
Yes, but if you have any update on this widget soon, I am ok with running #develop now.

**Comment by mikaelkaron** [comment]
None on my end. If i have not tagged this by monday pinh me and complain ;)

**Comment by yaoazhen** [comment]
Hi Mikael, How this going?

**Pull request merged**
